# pylint: skip-file
# Generated by Django 3.1.3 on 2020-12-07 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def insert_data(apps, schema_editor):
      ServerType = apps.get_model('wrangler', 'ServerType')
      vanilla = ServerType(name='Vanilla', docker_image='itzg/minecraft-server')
      vanilla.save()

    operations = [
        migrations.CreateModel(
            name='EnvironmentVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MineHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('docker_image', models.CharField(max_length=255)),
                ('environment_vars', models.ManyToManyField(to='wrangler.EnvironmentVar')),
            ],
        ),
        migrations.RunPython(insert_data),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('game_type', models.IntegerField(choices=[(0, 'Survival'), (1, 'Creative')], default=0)),
                ('port', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(25565), django.core.validators.MaxValueValidator(25693)])),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrangler.minehost')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('server_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wrangler.servertype')),
            ],
            options={
                'unique_together': {('host', 'port')},
            },
        ),
    ]
