# Generated by Django 3.1.3 on 2020-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_minecraftuser'),
        ('wrangler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='op_list',
            field=models.ManyToManyField(blank=True, to='accounts.MinecraftUser'),
        ),
    ]
