# Generated by Django 3.1.3 on 2020-12-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0002_server_op_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='minehost',
            name='max_port',
            field=models.IntegerField(default=25693),
        ),
        migrations.AddField(
            model_name='minehost',
            name='min_port',
            field=models.IntegerField(default=25565),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
