# Generated by Django 3.1.3 on 2021-01-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0004_auto_20201219_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
