# Generated by Django 3.1.3 on 2021-01-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0005_auto_20210102_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='minehost',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
