# Generated by Django 3.1.3 on 2021-01-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0006_minehost_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='servertype',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
