# Generated by Django 3.1.3 on 2021-01-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrangler', '0008_auto_20210117_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='minehost',
            name='server_limit',
            field=models.IntegerField(default=7),
        ),
    ]
