# Generated by Django 3.1.3 on 2020-12-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201219_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='server_limit',
            field=models.IntegerField(default=2),
        ),
    ]
